"""Small, dependency-free connectors for public country-level macro data.

World Bank Indicators API requires no API key. Global Findex indicators are
available through this API as well. OECD SDMX datasets vary by flow, so the
OECD helper accepts a CSV URL generated by OECD Data Explorer rather than
guessing a dataset or dimension order.
"""

from __future__ import annotations

import csv
import io
import json
import re
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import parse_qs, urlparse
from urllib.request import Request, urlopen


WORLD_BANK_BASE = "https://api.worldbank.org/v2"
OECD_HOUSEHOLD_DEBT_URL = (
    "https://sdmx.oecd.org/public/rest/data/"
    "OECD.SDD.NAD,DSD_FIN_DASH@DF_FIN_DASH_S1M,/"
    "A..LES1M_FD4.PT_B6N_S1M?startPeriod=2010&"
    "dimensionAtObservation=AllDimensions&format=csvfilewithlabels"
)
DEFAULT_INDICATORS = {
    "gdp_per_capita_usd": "NY.GDP.PCAP.CD",
    "gdp_growth_pct": "NY.GDP.MKTP.KD.ZG",
    "unemployment_pct": "SL.UEM.TOTL.ZS",
    "inflation_pct": "FP.CPI.TOTL.ZG",
    "population": "SP.POP.TOTL",
    # Global Findex; these observations are survey-year data, not annual data.
    "account_ownership_pct": "FX.OWN.TOTL.ZS",
    "account_ownership_poorest_40_pct": "FX.OWN.TOTL.40.ZS",
}
_INDICATOR_RE = re.compile(r"^[A-Z0-9_.]+$")
_INDICATOR_UNITS = {
    "gdp_per_capita_usd": "current US dollars per person",
    "gdp_growth_pct": "percent per year",
    "unemployment_pct": "percent of labor force",
    "inflation_pct": "percent per year",
    "population": "people",
    "account_ownership_pct": "percent of population ages 15+",
    "account_ownership_poorest_40_pct": "percent of population ages 15+",
}


def normalize_observation(
    country: str,
    year: int | str | None,
    metric: str,
    value: int | float | None,
    source: str,
    unit: str | None = None,
    source_indicator: str | None = None,
    source_label: str | None = None,
) -> dict[str, Any]:
    """Create the shared country/year/metric/value/source record.

    Use this for country-level Dealroom aggregates as well as external series.
    ``country`` should be an ISO-3 code; source-specific details stay optional.
    """
    normalized_year = int(year) if year is not None and str(year).isdigit() else None
    return {
        "country": country.upper() if country else None,
        "year": normalized_year,
        "metric": metric,
        "value": value,
        "source": source,
        "unit": unit,
        "source_indicator": source_indicator,
        "source_label": source_label,
    }


def _get_json(url: str, timeout: int = 20) -> Any:
    request = Request(url, headers={"Accept": "application/json", "User-Agent": "inclusive-alpha-hackathon/1.0"})
    try:
        with urlopen(request, timeout=timeout) as response:
            return json.loads(response.read().decode("utf-8"))
    except (HTTPError, URLError, TimeoutError) as exc:
        raise RuntimeError(f"Source request failed for {url}: {exc}") from exc


def fetch_world_bank(
    countries: list[str],
    start_year: int,
    end_year: int,
    indicators: dict[str, str] | None = None,
) -> list[dict[str, Any]]:
    """Return long-form country/year/indicator/value observations.

    ``countries`` must contain ISO-3 codes (for example GBR, FRA, BRA).
    Null observations are retained so missing coverage stays visible.
    """
    if not countries:
        raise ValueError("Provide at least one ISO-3 country code.")
    if start_year > end_year:
        raise ValueError("start_year must be less than or equal to end_year.")
    codes = indicators or DEFAULT_INDICATORS
    if not codes or any(not _INDICATOR_RE.fullmatch(code) for code in codes.values()):
        raise ValueError("Indicator codes must use letters, digits, underscores, and periods.")

    country_path = ";".join(code.upper() for code in countries)
    indicator_path = ";".join(codes.values())
    page = 1
    output: list[dict[str, Any]] = []
    while True:
        url = (
            f"{WORLD_BANK_BASE}/country/{country_path}/indicator/{indicator_path}"
            f"?format=json&source=2&date={start_year}:{end_year}&per_page=20000&page={page}"
        )
        payload = _get_json(url)
        if not isinstance(payload, list) or len(payload) < 2 or not isinstance(payload[1], list):
            raise RuntimeError(f"Unexpected World Bank response for {url}")
        metadata, rows = payload
        name_by_code = {code: name for name, code in codes.items()}
        for row in rows:
            code = row.get("indicator", {}).get("id")
            metric = name_by_code.get(code, code)
            output.append(normalize_observation(
                country=row.get("countryiso3code", ""),
                year=row.get("date"),
                metric=metric,
                value=row.get("value"),
                source="world_bank",
                unit=_INDICATOR_UNITS.get(metric),
                source_indicator=code,
                source_label=row.get("indicator", {}).get("value"),
            ))
        if page >= int(metadata.get("pages", 1)):
            break
        page += 1
    return output


def fetch_oecd_csv(url: str) -> list[dict[str, str]]:
    """Fetch a CSV-formatted OECD SDMX REST URL from Data Explorer.

    Select a dataset and measures in OECD Data Explorer, use its Developer
    API link, and choose CSV output if prompted. No OECD key is required for
    public datasets. The returned column names retain the OECD dimensions.
    """
    parsed = urlparse(url)
    if parsed.scheme != "https" or parsed.hostname != "sdmx.oecd.org":
        raise ValueError("Use an HTTPS URL hosted on sdmx.oecd.org.")
    query = parse_qs(parsed.query)
    if not any("csv" in value.lower() for values in query.values() for value in values):
        raise ValueError("Use the CSV-formatted URL provided by OECD Data Explorer.")
    request = Request(url, headers={"Accept": "text/csv", "User-Agent": "inclusive-alpha-hackathon/1.0"})
    try:
        with urlopen(request, timeout=30) as response:
            content = response.read().decode("utf-8-sig")
    except (HTTPError, URLError, TimeoutError) as exc:
        raise RuntimeError(f"OECD request failed: {exc}") from exc
    return list(csv.DictReader(io.StringIO(content)))


def fetch_oecd_household_debt() -> list[dict[str, str]]:
    """Return OECD annual household debt as a share of disposable income."""
    return fetch_oecd_csv(OECD_HOUSEHOLD_DEBT_URL)


if __name__ == "__main__":
    # Smoke the public connection with a compact UK and France sample.
    rows = fetch_world_bank(["GBR", "FRA"], 2021, 2024)
    for row in rows:
        print(row)
